apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: exam-lucstienne
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nathansegers/containers_23-24_december_backend:versie1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
