apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: exam-lucstienne
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 9000
      nodePort: 30001
  selector:
    app: backend