apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: exam-lucstienne
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: lucstienne/containers_23-24_december_frontend:versie1
          ports:
            - containerPort: 80
          env:
            - name: API_PORT
              value: "80"
            - name: API_HOST
              value: "api"
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"